### PR TITLE
ELK, Grafana, Prometheus were implemented

### LINKED ISSUE #8: Implement ELK + Prometheus + Grafana

### PR DESCRIPTION
**Pull request by vpetrovaa**
## PR-Codex overview
This PR adds logging, Prometheus monitoring, and Grafana visualization to the project. It also includes configuration files for Logstash, Kafka, Elasticsearch, and Kibana.

### Detailed summary
- Added logging to `NoteServiceImpl` methods
- Added Prometheus monitoring with configuration file
- Added Grafana visualization with configuration file
- Added `logstash.conf` configuration file
- Added `kafka` and `zookeeper` services and configuration files
- Added `elasticsearch` and `kibana` services and configuration files

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by vpetrovaa** [comment]
Kibana logs:

**Comment by vpetrovaa** [comment]
Kibana:
kibana

**Comment by vpetrovaa** [comment]
Prometheus:
prometheus

**Comment by vpetrovaa** [comment]
Grafana:
grafana

**Review by h1alexbel — APPROVED** [review]
lgtm

**Pull request merged**
